-- MultiLanguage_NL Dutch Items Translations v1
-- Generated by precache.py on 2026-03-20 19:27
-- Total items: 28305
-- Dataset version: 1

MultiLanguageItemData = MultiLanguageItemData or {}
MultiLanguageItemData['nl'] = {}
