-- MultiLanguage_NL Dutch Spells Translations v1
-- Generated by precache.py on 2026-03-20 17:52
-- Total spells: 341896
-- Dataset version: 1

MultiLanguageSpellData = MultiLanguageSpellData or {}
MultiLanguageSpellData['nl'] = {}
